### ISSUE TITLE
融资金额似乎只反映最新一轮而不是总量

### ISSUE THREAD

**Issue by YikSanChan** [WarrenWen666/AI-Software-Startups#3]
Hi @WarrenWen666 ，谢谢你的整理！

我发现 https://github.com/WarrenWen666/AI-Software-Startups/blob/main/SSAIS_MLOps.md 的融资金额只反映最新一轮而不是总量。例如：

- Tecton B 轮融资 $35m 但总融资是 $60m
- DataRobot G 轮融资 $250m 但总融资是 $1b

请问这是 by design 的吗？谢谢

**Comment by WarrenWen666** [comment]
谢谢支持！
对的，这个repo采用了最新一轮的融资金额而没有采用累积融资总额。反映Startup价值的比较好的指标，既不是最新一轮的融资额，也不是累积融资总额，而是最新一轮的估值。但是很多Startup的估值，只有达到了独角兽才会披露出来。所以只能选融资金额或累积融资总额来估算Startup估值。采用累积融资总额来估算Startup估值有一些不足，例如有一些Startup发展一般，所以连续几轮估值几乎没有增长，但是总融资额成倍增长。一般一轮融资，Startup会出让10~20%的股份，相当于估值大概是最新一轮融资额5~10倍。所以采用最新一轮的融资金额应该会比累积融资总额更能反映Startup的估值。

如果你觉得采用累积融资总额比较合适，欢迎给出理由~ 如果言之有理，也可以改成累积融资总额

**Comment by WarrenWen666** [comment]
> Hi @WarrenWen666 ，谢谢你的整理！
> 
> 我发现 https://github.com/WarrenWen666/AI-Software-Startups/blob/main/SSAIS_MLOps.md 的融资金额只反映最新一轮而不是总量。例如：
> 
> * Tecton B 轮融资 $35m 但总融资是 $60m
> * DataRobot G 轮融资 $250m 但总融资是 $1b
> 
> 请问这是 by design 的吗？谢谢

谢谢支持！
对的，这个repo采用了最新一轮的融资金额而没有采用累积融资总额。反映Startup价值的比较好的指标，既不是最新一轮的融资额，也不是累积融资总额，而是最新一轮的估值。但是很多Startup的估值，只有达到了独角兽才会披露出来。所以只能选融资金额或累积融资总额来估算Startup估值。采用累积融资总额来估算Startup估值有一些不足，例如有一些Startup发展一般，所以连续几轮估值几乎没有增长，但是总融资额成倍增长。一般一轮融资，Startup会出让10到20%的股份，相当于估值大概是最新一轮融资额5到10倍。所以采用最新一轮的融资金额应该会比累积融资总额更能反映Startup的估值。

如果你觉得采用累积融资总额比较合适，欢迎给出理由~ 如果言之有理，也可以改成累积融资总额

**Comment by YikSanChan** [comment]
> 一般一轮融资，Startup会出让10到20%的股份，相当于估值大概是最新一轮融资额5到10倍。

嗯嗯明白，那也合理的。 👍 那维持现状就挺好
