### ISSUE TITLE
微信群二维码失效

### ISSUE THREAD

**Issue by YikSanChan** [WarrenWen666/AI-Software-Startups#4]
Hi @WarrenWen666 感谢你的整理和分享。

你在 https://github.com/WarrenWen666/AI-Software-Startups/blob/main/SSAIS_MLOps.md 贴出的微信群聊二维码失效了，主要是微信的锅。

**Comment by WarrenWen666** [comment]
对，微信群二维码一个星期就失效。所以可以加我微信，我拉入群聊。我已经把你拉入群聊~
